# Generated by Django 5.1.4 on 2025-01-19 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PermissionType",
            fields=[
                ("permission_id", models.AutoField(primary_key=True, serialize=False)),
                ("permission", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("matricula", models.IntegerField()),
                ("primeiro_nome", models.CharField(max_length=100)),
                ("ultimo_nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("situacao", models.TextField(default="Trabalhando")),
                ("telefone", models.TextField(default="4712345678")),
                ("password", models.CharField(max_length=100)),
                (
                    "permission",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storage_customuser.permissiontype",
                    ),
                ),
            ],
        ),
    ]
