# Generated by Django 5.1.4 on 2025-02-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage_customuser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="permission",
            field=models.CharField(
                choices=[
                    ("ADMINISTRADOR", "Administrador"),
                    ("SOMENTE LEITURA", "Somente Leitura"),
                ],
                default="Somente Leitura",
                max_length=20,
            ),
        ),
    ]
