# Generated by Django 5.1.5 on 2025-01-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_customuser', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.TextField(default='4712345678'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.TextField(default='Trabalhando'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
