# Generated by Django 5.1.5 on 2025-01-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_customuser', '0003_customuser_phone_number_customuser_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
