"""
Django settings for storage_config project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta


BASE_DIR = Path(__file__).resolve().parent.parent
# Quick-start development settings - unsuitable for production
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

SECRET_KEY = "django-insecure-n3+)-$8nsi9!_a4^mcpgt@9f+8=j+7*0au%4ysn2t8bxscb(mo"


DEBUG = True
ALLOWED_HOSTS = []

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "storage_management",
    "storage_customuser",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SESSION_COOKIE_AGE = 60 * 60 
SESSION_EXPIRE_AT_BROWSER_CLOSE = False


CSRF_COOKIE_NAME = 'csrftoken'  # Nome do cookie CSRF
CSRF_COOKIE_HTTPONLY = False  # Permite acesso ao cookie via JavaScript
CSRF_COOKIE_SAMESITE = 'None'  # Permite o CSRF em cookies cross-origin
CORS_ALLOW_CREDENTIALS = True  # Permite o envio de cookies entre domínios
CORS_ALLOWED_ORIGINS = [
    'http://localhost:8000',
    'http://localhost:5173',
]
CORS_ALLOW_CREDENTIALS = True  # Permite o envio de cookies
APPEND_SLASH = False

SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'  # Usando sessões com cookies
SESSION_COOKIE_NAME = "sessionid"

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

# Configuração do tempo de expiração do JWT
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  # Token de acesso expira em 60 minutos
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # Token de refresh expira em 7 dias
    'ROTATE_REFRESH_TOKENS': False,  # Se você não quiser rotacionar o refresh token
    'BLACKLIST_AFTER_ROTATION': False,  # Se você não quiser bloquear tokens após a rotação
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = "storage_config.urls"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "storage_config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "storage_customuser.CustomUser"