# Generated by Django 5.1.4 on 2025-02-04 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("id_categoria", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nome",
                    models.CharField(
                        default="", max_length=50, verbose_name="Nome da Categoria"
                    ),
                ),
                (
                    "descricao_categoria",
                    models.CharField(
                        max_length=500, verbose_name="Descrição da Categoria"
                    ),
                ),
                (
                    "localizacao",
                    models.CharField(max_length=500, verbose_name="Localização"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                ("id_fornecedor", models.AutoField(primary_key=True, serialize=False)),
                (
                    "razao_social",
                    models.CharField(max_length=500, verbose_name="Razão Social"),
                ),
                (
                    "nome_fantasia",
                    models.CharField(max_length=500, verbose_name="Nome Fantasia"),
                ),
                ("cnpj", models.CharField(max_length=15, verbose_name="CNPJ")),
                (
                    "inscricao_estadual",
                    models.CharField(max_length=9, verbose_name="Inscrição Estadual"),
                ),
                ("telefone", models.IntegerField(verbose_name="Telefone")),
                ("endereco", models.CharField(max_length=500, verbose_name="Endereço")),
                (
                    "tipo_produto",
                    models.CharField(max_length=500, verbose_name="Tipo de Produto"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                ("id_produto", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nome_produto",
                    models.CharField(max_length=500, verbose_name="Nome do Produto"),
                ),
                ("quantidade", models.IntegerField(verbose_name="Quantidade")),
                (
                    "codigo_produto",
                    models.CharField(max_length=13, verbose_name="Código do Produto"),
                ),
                ("preco_produto", models.FloatField(verbose_name="Preço do Produto")),
                ("status", models.BooleanField(default=True, verbose_name="Status")),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storage_management.categoria",
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storage_management.fornecedor",
                    ),
                ),
            ],
        ),
    ]
