# Generated by Django 5.1.4 on 2025-02-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage_management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="nome",
            field=models.CharField(
                default="", max_length=50, verbose_name="Nome da Categoria"
            ),
        ),
    ]
